.PHONY: all 

all:
#	make -C pte_test
	make -C newlib_test
#	make -C semaphore_test
#	make -C helloworld
clean:
#	make -C pte_test clean
	make -C newlib_test clean
#	make -C semaphore_test clean
#	make -C helloworld clean
