// SPDX-FileCopyrightText: Copyright (c) 2021 Electronics and Telecommunications Research Institute
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef __OFFLOAD_MEMORY_CONFIG_H__
#define __OFFLOAD_MEMORY_CONFIG_H__

#include "memory_config.h"

#define CONFIG_OFFLOAD_CHANNEL_VA	(CONFIG_SHARED_MEMORY + CHANNEL_START_OFFSET + 300*1024UL*1024UL)
#define OFFLOAD_CHANNEL_LOCK_VA		(CONFIG_OFFLOAD_CHANNEL_VA)	
#define OFFLOAD_CHANNEL_STRUCT_VA	(CONFIG_OFFLOAD_CHANNEL_VA + (PAGE_SIZE_4K * 100))
#define OFFLOAD_CHANNEL_INFO_VA		(CONFIG_OFFLOAD_CHANNEL_VA + (PAGE_SIZE_4K * 200))
#define OFFLOAD_CHANNEL_BASE_VA		(CONFIG_OFFLOAD_CHANNEL_VA + (PAGE_SIZE_4K * 300))

#endif // __OFFLOAD_MEMORY_CONFIG_H__
