#ifndef __OFFLOAD_MEMORY_CONFIG_H__
#define __OFFLOAD_MEMORY_CONFIG_H__

#include "arch.h"

#define UNIKERNELS_MEM_BASE_PA  ((unsigned long) UNIKERNEL_START << 30)          // UNIKERNEL_START
#define UNIKERNELS_MEM_SIZE     (((unsigned long) MEMORYS_PER_NODE << 30) * 7)   // assume max # of unikernel is 7

#define CONFIG_SHARED_MEMORY_PA	((unsigned long) (UNIKERNEL_START-SHARED_MEMORY_SIZE+CHANNEL_START_OFFSET) << 30)

#define	OFFLOAD_LOCK_ENABLE

#define OFFLOAD_CHANNEL_LOCK_PA (CONFIG_SHARED_MEMORY_PA)	
#define OFFLOAD_CHANNEL_STRUCT_PA (CONFIG_SHARED_MEMORY_PA + (PAGE_SIZE_4K * 100))
#define OFFLOAD_CHANNEL_INFO_PA (CONFIG_SHARED_MEMORY_PA + (PAGE_SIZE_4K * 200))
#define OFFLOAD_CHANNEL_BASE_PA (CONFIG_SHARED_MEMORY_PA + (PAGE_SIZE_4K * 300))

#define CONFIG_SHARED_MEMORY_VA	(0xFFFF800080000000)
#define OFFLOAD_CHANNEL_LOCK_VA (CONFIG_SHARED_MEMORY_VA)	
#define OFFLOAD_CHANNEL_STRUCT_VA (CONFIG_SHARED_MEMORY_VA + (PAGE_SIZE_4K * 100))
#define OFFLOAD_CHANNEL_INFO_VA (CONFIG_SHARED_MEMORY_VA + (PAGE_SIZE_4K * 200))
#define OFFLOAD_CHANNEL_BASE_VA (CONFIG_SHARED_MEMORY_VA + (PAGE_SIZE_4K * 300))

#define OFFLOAD_MAX_CHANNEL     (300)
#define OFFLOAD_MAGIC           (0x5D4C3B2A)

#define OFFLOAD_N_NODE          (3)

#endif
// __OFFLOAD_MEMORY_CONFIG_H__
