#ifndef __OFFLOAD_MEMORY_CONFIG_H__
#define __OFFLOAD_MEMORY_CONFIG_H__

#define UNIKERNELS_MEM_BASE_PA  ((unsigned long) 48 * 1024 * 1024 * 1024)       // 48G 
#define UNIKERNELS_MEM_SIZE     ((unsigned long) 48 * 3 *1024 * 1024 * 1024)    // 48G * 3

// reference this value from "memory_config.h" in unikernel
#define CONFIG_SHARED_MEMORY        (0xA80000000)                               // 42GB

#define CONFIG_SHARED_MEMORY_PA	(CONFIG_SHARED_MEMORY)

#define OFFLOAD_CHANNEL_LOCK_PA (CONFIG_SHARED_MEMORY_PA)	
#define OFFLOAD_CHANNEL_STRUCT_PA (CONFIG_SHARED_MEMORY_PA + (PAGE_SIZE_4K * 2))
#define OFFLOAD_CHANNEL_INFO_PA (CONFIG_SHARED_MEMORY_PA + (PAGE_SIZE_4K * 10))
#define OFFLOAD_CHANNEL_BASE_PA (CONFIG_SHARED_MEMORY_PA + (PAGE_SIZE_4K * 11))

#define CONFIG_SHARED_MEMORY_VA	(0xFFFF800080000000)
#define OFFLOAD_CHANNEL_LOCK_VA (CONFIG_SHARED_MEMORY_VA)	
#define OFFLOAD_CHANNEL_STRUCT_VA (CONFIG_SHARED_MEMORY_VA + (PAGE_SIZE_4K * 2))
#define OFFLOAD_CHANNEL_INFO_VA (CONFIG_SHARED_MEMORY_VA + (PAGE_SIZE_4K * 10))
#define OFFLOAD_CHANNEL_BASE_VA (CONFIG_SHARED_MEMORY_VA + (PAGE_SIZE_4K * 11))


#define OFFLOAD_MAX_CHANNEL     (300)
#define OFFLOAD_MAGIC           (0x5D4C3B2A)

#endif
// __OFFLOAD_MEMORY_CONFIG_H__
