#ifndef __CONSOLE_MEMORY_CONFIG_H__
#define __CONSOLE_MEMORY_CONFIG_H__

#include "arch.h"

#define UNIKERNELS_MEM_BASE_PA		((unsigned long)(UNIKERNEL_START *1024UL*1024UL*1024UL)) 

#define CONFIG_CONSOLE_CHANNEL_PA	((unsigned long) (UNIKERNEL_START - SHARED_MEMORY_SIZE + CHANNEL_START_OFFSET)*1024UL*1024UL*1024UL)
#define CONSOLE_CHANNEL_STRUCT_PA	(CONFIG_CONSOLE_CHANNEL_PA)
#define CONSOLE_CHANNEL_BASE_PA		(CONFIG_CONSOLE_CHANNEL_PA + PAGE_SIZE_4K)

#define CONSOLE_CHANNEL_NUM             (MAX_NODE_NUM) // 1 channel / node
#define CONSOLE_CHANNEL_CQ_ELEMENT_NUM  (4)

#endif
// __CONSOLE_MEMORY_CONFIG_H__
