#ifndef __CONSOLE_MEMORY_CONFIG_H__
#define __CONSOLE_MEMORY_CONFIG_H__

#include "memory_config.h"

/*
#define CONFIG_OFFLOAD_CHANNEL_VA	(CONFIG_SHARED_MEMORY + (CHANNEL_START_OFFSET << 30))
#define OFFLOAD_CHANNEL_LOCK_VA		(CONFIG_OFFLOAD_CHANNEL_VA)	
#define OFFLOAD_CHANNEL_STRUCT_VA	(CONFIG_OFFLOAD_CHANNEL_VA + (PAGE_SIZE_4K * 100))
#define OFFLOAD_CHANNEL_INFO_VA		(CONFIG_OFFLOAD_CHANNEL_VA + (PAGE_SIZE_4K * 200))
#define OFFLOAD_CHANNEL_BASE_VA		(CONFIG_OFFLOAD_CHANNEL_VA + (PAGE_SIZE_4K * 300))
*/

#define CONSOLE_CHANNEL_VA       (CONFIG_SHARED_MEMORY + (CHANNEL_START_OFFSET << 30))
#define CONSOLE_CHANNEL_STRUCT_VA       (CONSOLE_CHANNEL_VA)
#define CONSOLE_CHANNEL_BASE_VA         (CONSOLE_CHANNEL_VA + PAGE_SIZE_4K)

#define CONSOLE_CHANNEL_NUM             (MAX_NODE_NUM) // 1 channel / node
#define CONSOLE_CHANNEL_CQ_ELEMENT_NUM  (4)


#endif
// __OFFLOAD_MEMORY_CONFIG_H__
